### ISSUE TITLE
chat exporter "can't find valid module"

### ISSUE THREAD

**Issue by jrax7** [Fear-and-Terror-EU-Programming-Team/fear-and-terror-ticket-bot#5] opened 2021-05-13 10:22 UTC

**Comment by w4rum** [comment] 2021-05-13 12:27
I'll need a little more than that to help you.

**Comment by jrax7** [comment] 2021-05-13 12:41
This is my discord 
Jrx7#0611

**Comment by w4rum** [comment] 2021-05-13 16:10
If you want to tell me about an issue, then please provide a more detailed report. I can't reproduce an issue after just reading
> chat exporter "can't find valid module" 

I'm not going to add you on Discord and try to pry that information out of you. I've got other work to do and, frankly, it's not my problem. Please provide more details *here in this GitHub issue* or close the issue.

**Comment by jrax7** [comment] 2021-05-13 19:52
About the discord thingy was trying to make it more simple in terms of contact and it would be easier since if you didn't get my point I could send you screenshots in a much easier way.

This is the message I received:

` line 10, in <module>
    import chat_exporter
ModuleNotFoundError: No module named 'chat_exporter' `

**Comment by w4rum** [comment] 2021-05-14 11:11
> I could send you screenshots in a much easier way

It might not be that obvious but you can actually post screenshots here by just hitting CTRL+V in the comment window. It's just as easy as in Discord.

I'll look into it.

**Comment by w4rum** [comment] 2021-05-14 11:14
I think you missed installing the required dependencies. Check the README:

> You can install these via `pip install -r requirements.txt`

If you think you've installed everything correctly and it still doesn't work, then please provide me with a detailed list of steps you did to arrive at this error and I'll check if anything seems off.

**Comment by jrax7** [comment] 2021-05-14 11:24
Does it not work on replit, because if that's the case then I think am doing it wrong. Or is there a way I can get it on replit or do I have to use my CMD and external python programs?

**Comment by w4rum** [comment] 2021-05-14 12:05
Until now I've never heard of replit. So I can't give you any help with that. See if you can install dependencies in there.

**Comment by w4rum** [comment] 2021-05-20 20:53
Closing for inactivity / Problem with deployment, not the project.

**Closed as completed by w4rum** 2021-05-20 20:53 UTC
